[package]
name = "storq"
version = "0.1.0"
authors = ["FeÌlix Saparelli <felix@passcod.name>"]
edition = "2018"

[dependencies]
sled = "0.28.0"
byteorder = "1.3.2"
serde = "1.0.92"
bincode = "1.1.4"
lazy_static = "1.3.0"
wasmer-runtime = "0.7.0"
